server.port: ${greeting-service.port}

service:
  cute-name:
    name: ${cute-name-service.endpoint}
spring:
  application:
    name: ${project.artifactId}
  sleuth:
    otel:
      config:
        # The trace-id-ratio-based property defines the sampling ratio for the spans collected.
        # The value 1.0 means that all spans will be exported.
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: ${jaeger.endpoint}

# Dekorate
dekorate:
  openshift:
    name: greeting-service
  s2i:
    builder-image: registry.access.redhat.com/ubi8/openjdk-11:1.14
